# Postgres Container Set-Up

services:
  postgresql:
    image: postgres:13.4-alpine
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: weather_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes: 
      - database-data:/var/lib/postgresql/data/
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin:

#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 30s
#      timeout: 30s
#      retries: 3
#    logging:
#      driver: syslog
#      options:
#        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
#    networks:
#      - backend
#    restart: on-failure
#    volumes:
#      - ${PWD}/postgres/data:/var/lib/postgresql/data